### ISSUE TITLE
`responsive-image-test`

### ISSUE THREAD

**Issue by OliverJAsh** [ryuran/sizes-webextension#10]
Hi,

I have written a module to do a very similar thing named [`responsive-image-test`](https://github.com/unsplash/responsive-image-test).

Example usage:

``` ts
getSizesAndLog(myImageEl);
// => { currentSrcWidth: 2000, elementWidth: 1800, parsedSize: 1800 }
```

I wrote about this here: https://medium.com/unsplash/how-we-test-responsive-images-at-unsplash-4fb940caee72

The benefit of having the logic in a module, separate from the extension, is it allows it to be used programmatically. For example, we use this module in our E2E tests, to make assertions against our responsive images.

I wonder if there's any potential overlap between this extension and my module. How are they different? Could this extension re-use `responsive-image-test`?

**Comment by OliverJAsh** [comment]
One difference is that `responsive-image-test` also calculates the `currentSrcWidth` (the width of the `currentSrc` chosen from `srcset`). This allows you to easily compare whether the image that's actually used corresponds to the image element's width.

The only other difference seems to be how we convert the parsed size string into a width number.

This extension:

``` ts
const parsedSizeStrToWidth = (str: string): number => {
    const node = document.createElement('div')
    node.style.width = str;
    return node.getBoundingClientRect().width;
}
```

`responsive-image-test`:

``` ts
const parsedSizeStrToWidth = (str: string): string => {
    const node = document.createElement('div')
    node.style.width = str;
    document.body.appendChild(node);
    const { width } = window.getComputedStyle(node);
    document.body.removeChild(node);
    return width as string;
}
```

I have no idea if there is any meaningful difference here.

If you wanted to use `responsive-image-test`, you could do:

``` ts
import { getSizes } from 'responsive-image-test';

ImagesSizes.prototype.testSizes = function testSizes(el) {
    const result = getSizes(el);
    return almostEqual(result.parsedSize, result.elementWidth);
};
```

**Comment by ryuran** [comment]
@OliverJAsh Hi, and thanks for this issue.

# I reuse the same div

In this extension I reuse the same element for each test to not add and remove a `<div>` in DOM tree for each elements.
https://github.com/ryuran/sizes-webextension/blob/master/src/imagesSizes.js#L44-L47

# I set some CSS rules

This `<div>` have some style to not be impacted by other CSS
https://github.com/ryuran/sizes-webextension/blob/master/src/imagesSizes.js#L9-L15

In your case, it’s not needed because you use `getComputedStyle`

# `getComputedStyle`

I'm not sure what is the best solution, `getComputedStyle(node).width` or `node.getBoundingClientRect().width`

If you have test, on your project maybe you can compare it ?
